name: Doc


on:
  push:
    branches:
      - main

env:
  PY_COLORS: 1

jobs:
  sphinx:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.0
      - name: Set up Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install tox
      - name: Build doc
        env:
          TOXENV: doc
        run: tox
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_build/sphinx # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
