name: Release

on:
  workflow_dispatch:

jobs:
  inputs:
    runs-on: ubuntu-latest
    outputs:
      force_arg: ${{ steps.init.outputs.force_arg }}
    environment: pypi.org
    steps:
      - id: init
        name: Analyze input arguments
        run: |
          if [ "${{ secrets.RELEASE_TYPE }}" != "Auto"]; then
            echo "force_arg=${{ secrets.RELEASE_TYPE }}" >> ${GITHUB_OUTPUT}
          else
            echo "force_arg=" >> ${GITHUB_OUTPUT}
          fi

  release:
    if: github.repository == 'sismicfr/pypdffiller'
    needs: inputs
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    environment: pypi.org
    outputs:
      released: ${{ steps.release.outputs.released }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}

      - name: Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
          force: ${{ needs.inputs.outputs.force_arg }}

      - uses: actions/upload-artifact@v4
        if: steps.release.outputs.released == 'true'
        with:
          name: unbutun-build
          path: ./installer/dist/*.tar.gz

      - uses: actions/upload-artifact@v4
        if: steps.release.outputs.released == 'true'
        with:
          name: python-build
          path: ./dist/*

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: steps.release.outputs.released == 'true'
        with:
          skip-existing: true
          verbose: true

  debian-build:
      needs: [release]
      runs-on: ubuntu-latest
      concurrency: debian-build
      permissions:
        id-token: write
        contents: write
      environment: pypi.org
      if: github.repository == 'sismicfr/pypdffiller' && needs.release.outputs.released == 'true'
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ needs.release.outputs.tag }}
            token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
        - name: Build executable
          run: |
            make debian-exe
        - uses: actions/upload-artifact@v4
          with:
            name: debian-build
            path: ./installer/dist/*.tar.gz

  alpine-build:
      needs: [release]
      runs-on: ubuntu-latest
      concurrency: debian-build
      permissions:
        id-token: write
        contents: write
      environment: pypi.org
      if: github.repository == 'sismicfr/pypdffiller' && needs.release.outputs.released == 'true'
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ needs.release.outputs.tag }}
            token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
        - name: Build executable
          run: |
            make alpine-exe
        - uses: actions/upload-artifact@v4
          with:
            name: alpine-build
            path: ./installer/dist/*.tar.gz

  release-notes:
      if: github.repository == 'sismicfr/pypdffiller' && needs.release.outputs.released == 'true'
      needs: [release, debian-build, alpine-build]
      runs-on: ubuntu-latest
      concurrency: publish
      permissions:
        id-token: write
        contents: write
      environment: pypi.org
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ needs.release.outputs.tag }}
            token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
        - uses: actions/download-artifact@v5
          with:
            name: debian-build
            path: installer/dist
        - uses: actions/download-artifact@v5
          with:
            name: alpine-build
            path: installer/dist
        - uses: actions/download-artifact@v5
          with:
            name: python-build
            path: dist
        - name: Publish package to GitHub Releases
          uses: python-semantic-release/publish-action@v1
          with:
            github_token: ${{ secrets.RELEASE_GITHUB_TOKEN  }}
            tag: ${{ needs.release.outputs.tag }}